#!/bin/bash

# Preserves deepest hierarchy level and drops file extension
stack_name=${1##*/}
stack_name=${stack_name%%.*}

# Runs cloud formation
aws cloudformation delete-stack --stack-name ${stack_name}
