AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a private and public subnets with NAT and Bastion EC2 instance
Parameters:
  KeyPairName:
    Description:     EC2 KeyPair.
    Type:           'AWS::EC2::KeyPair::KeyName'
    MinLength:       2
    ConstraintDescription:  must not be blank.

  VpcCidr:
    Description:    VPC CIDR
    Type:           String
    Default:        '10.0.0.0/16'

  PublicSubnetCidr:
    Description:    Public subnet CIDR
    Type:           String
    Default:        '10.0.0.0/24'

  PrivateSubnetCidr:
    Description:    Private subnet CIDR
    Type:           String
    Default:        '10.0.1.0/24'

  SshCidr:
    Description:    SSH location
    Type:           String
    Default:        '0.0.0.0/0'

  EC2InstanceType:
    Description:    Amazon EC2 instance type.
    Type:           String
    Default:        "t2.micro"
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - t2.xlarge
    - t2.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge
    - m4.16xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
    - m5.12xlarge
    - m5.24xlarge
    - m5d.large
    - m5d.xlarge
    - m5d.2xlarge
    - m5d.4xlarge
    - m5d.12xlarge
    - m5d.24xlarge

Mappings:
  Arch2AMI:
    us-east-1:
      HVM64: ami-6869aa05
    us-west-2:
      HVM64: ami-7172b611
    us-west-1:
      HVM64: ami-31490d51
    eu-west-1:
      HVM64: ami-f9dd458a
    eu-central-1:
      HVM64: ami-ea26ce85
    ap-northeast-1:
      HVM64: ami-374db956
    ap-northeast-2:
      HVM64: ami-2b408b45
    ap-southeast-1:
      HVM64: ami-a59b49c6
    ap-southeast-2:
      HVM64: ami-dc361ebf
    ap-south-1:
      HVM64: ami-ffbdd790
    us-east-2:
      HVM64: ami-f6035893
    sa-east-1:
      HVM64: ami-6dd04501
    cn-north-1:
      HVM64: ami-8e6aa0e3

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Ref VpcCidr
      Tags:
      - Key: Application
        Value:
          Ref: 'AWS::StackName'
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref Vpc
      GroupDescription: SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref SshCidr
      Tags:
      - Key: Application
        Value:
          Ref: 'AWS::StackName'
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  GatewayAttachement:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      MapPublicIpOnLaunch: true
      VpcId: !Ref Vpc
      CidrBlock: !Ref PublicSubnetCidr
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs: {Ref: 'AWS::Region'}
      Tags:
      - Key: Application
        Value:
          Ref: 'AWS::StackName'
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachement
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      RouteTableId: !Ref PublicRouteTable
      GatewayId: !Ref InternetGateway
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable
  NatGatewayAttachment:
    Type: AWS::EC2::EIP
    DependsOn: GatewayAttachement
    Properties:
      Domain: vpc
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayAttachment.AllocationId
      SubnetId: !Ref PublicSubnet
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !Ref PrivateSubnetCidr
      AvailabilityZone:
        Fn::Select:
        - 1
        - Fn::GetAZs: {Ref: 'AWS::Region'}
      Tags:
      - Key: Application
        Value:
          Ref: 'AWS::StackName'
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc
  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PrivateRouteTable
      NatGatewayId: !Ref NatGateway
  PrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet
  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref EC2InstanceType
      ImageId: !FindInMap [Arch2AMI, !Ref 'AWS::Region', 'HVM64']
      NetworkInterfaces:
      - NetworkInterfaceId: !Ref PublicEth0
        DeviceIndex: '0'
      KeyName: !Ref KeyPairName
      Tags:
      - Key: Application
        Value:
          Ref: 'AWS::StackName'
  PublicEth0:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: eth0
      GroupSet: [!Ref SSHSecurityGroup]
      SourceDestCheck: 'true'
      SubnetId: !Ref PublicSubnet
      Tags:
      - Key: Name
        Value: Interface 0
      - Key: Interface
        Value: eth0

  # Private instance setup below.
  # The private instance could be an actual worker instance which does the work like
  # processing SQS messages for example
  PrivateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref EC2InstanceType
      ImageId: !FindInMap [Arch2AMI, !Ref 'AWS::Region', 'HVM64']
      NetworkInterfaces:
      - NetworkInterfaceId: !Ref PrivateEth0
        DeviceIndex: '0'
      KeyName: !Ref KeyPairName
      Tags:
      - Key: Application
        Value:
          Ref: 'AWS::StackName'
  PrivateEth0:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: eth0
      GroupSet: [!Ref SSHSecurityGroup]
      SourceDestCheck: 'true'
      SubnetId: !Ref PrivateSubnet
      Tags:
      - Key: Name
        Value: Interface 0
      - Key: Interface
        Value: eth0

Outputs:
  BastionPublicUrl:
    Description: The public URL of the bastion instance to establish SSH tunnel
    Value: !GetAtt BastionInstance.PublicDnsName
  PrivateInstanceIpAddress:
    Description: The IP Address of the secure EC2 instance in a private subnet
    Value: !GetAtt PrivateEC2Instance.PrivateIp
